---
id: omotesandorb-53
base_name: slide
tags: ['ruby', 'Re:VIEW']
presentation_date: 2019-12-05
presentation_start_time: 
presentation_end_time: 
version: 1.0.0
licenses: ['MIT']
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user: 
  speaker_deck_user: 
